version: "3.3"
services:
  redis:
    image: redis:5.0
    ports:
      - 6378:6379
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
      - celery
      - celery_beat
      - db
    volumes:
      - .:/web_hook_create
    ports:
      - 8001:8000
    env_file:
      - .env
  celery:
    build: .
    command: celery -A webhook_creator_api worker -l INFO
    volumes:
      - .:/web_hook_create
    depends_on:
      - redis
      - db
    env_file:
      - .env
  celery_beat:
    build: .
    command: celery -A webhook_creator_api beat -l INFO
    volumes:
      - .:/web_hook_create
    depends_on:
      - redis
      - celery
      - db
    env_file:
      - .env
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3304:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hello_django
      - MYSQL_DATABASE=db

volumes:
  mysql_data:
